spring.application.name=backend
server.port = 8000


elexon.base-url = https://data.elexon.co.uk/bmrs/api/v1/datasets
elexon.data-from=2024-01-01
elexon.data-to=2024-01-31

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=10,expireAfterWrite=24h

logging.level.com.windforecast=INFO
